
title: CulturaEduca - Dashboards e Geocodificação
description: Projeto de TCC sobre visualização de dados e software livre para geocodificação aplicados à plataforma CulturaEduca.
theme: just-the-docs

url: https://sabrizzs.github.io/tcc-culturaeduca

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
